### PR TITLE
Update toolchain to musl-cross-make

### PR DESCRIPTION
**Pull request by bcook-r7**
https://github.com/busterb/musl-cross-make

### CODE REVIEW

**Comment by acammack-r7** [comment]
Currently won't build `arm-linux-musleabihf` :(
```
Building target arm-linux-musleabihf
Unpacking mbedtls for arm-linux-musleabihf
Building mbedtls for arm-linux-musleabihf
Unpacking curl for arm-linux-musleabihf
Configuring curl for arm-linux-musleabihf
configure: WARNING: Continuing even with errors mentioned immediately above this line.
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: the previous check could not be made default was used
configure: WARNING: skipped the ca-cert path detection when cross-compiling
Building curl for arm-linux-musleabihf
formdata.c: In function 'FormAdd':
formdata.c:390:21: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         array_state?(curl_off_t)array_value:va_arg(params, curl_off_t);
                     ^
Configuring libdnet for arm-linux-musleabihf
configure: WARNING: using cross tools not prefixed with host triplet
Building libdnet for arm-linux-musleabihf
Configuring json-c for arm-linux-musleabihf
configure: WARNING: using cross tools not prefixed with host triplet
Building json-c for arm-linux-musleabihf
Configuring libsigar for arm-linux-musleabihf
configure: WARNING: using cross tools not prefixed with host triplet
Building libsigar for arm-linux-musleabihf
Configuring libuv for arm-linux-musleabihf
configure: WARNING: using cross tools not prefixed with host triplet
Building libuv for arm-linux-musleabihf
Configuring mettle for arm-linux-musleabihf
configure: WARNING: using cross tools not prefixed with host triplet
Building mettle for arm-linux-musleabihf
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: error: mettle uses VFP register arguments, /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(memcmp.o) does not
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: failed to merge target specific data of file /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(memcmp.o)
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: error: mettle uses VFP register arguments, /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(intf.o) does not
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: failed to merge target specific data of file /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(intf.o)
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: error: mettle uses VFP register arguments, /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(route-linux.o) does not
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: failed to merge target specific data of file /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(route-linux.o)
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: error: mettle uses VFP register arguments, /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(addr.o) does not
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: failed to merge target specific data of file /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(addr.o)
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: error: mettle uses VFP register arguments, /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(addr-util.o) does not
/home/acammack/mettle/build/tools/musl-cross/bin/../lib/gcc/arm-linux-musleabihf/5.3.0/../../../../arm-linux-musleabihf/bin/ld: failed to merge target specific data of file /home/acammack/mettle/build/cross-arm-linux-musleabihf/lib/libdnet.a(addr-util.o)
collect2: error: ld returned 1 exit status
make[2]: *** [mettle] Error 1
make[1]: *** [install-recursive] Error 1
make/Makefile.mettle:19: recipe for target '/home/acammack/mettle/build/cross-arm-linux-musleabihf/mettle.built' failed
make: *** [/home/acammack/mettle/build/cross-arm-linux-musleabihf/mettle.built] Error 2
```

**Comment by busterb** [comment]
Not seeing this problem locally - possibly need to blow away the build objects and try again.

**Comment by acammack-r7** [comment]
That must have been it. On to making sure they still work!

**Comment by acammack-r7** [comment]
Sweet. Looks like everything is building fine.

**Pull request merged**
