### PR TITLE
Mettlesploit!

### PR DESCRIPTION
**Pull request by busterb**
This adds new capabilities to Mettle, allowing it to operate as an independent loader and executor of Metasploit modules. This only adds simple support for Coldstone style external modules (see https://blog.rapid7.com/2017/12/28/regifting-python-in-metasploit/ and https://github.com/rapid7/metasploit-framework/wiki/Writing-External-Python-Modules) but potentially other styles could be added as well.

Also of note, this adds a console dispatcher and an RPC listener, making it possible to build full-fledged control capabilities into Mettle as well. One could use it as a listener, console, payload, and more, with a single binary.

Thanks to @acammack-r7 for developing the initial Coldstone API, all of the contributors to that project, @zerosum0x0 and @jennamagius for console tweaks that we never quite got working in metasploit-framework reliably.

Demo:

```
$ export PYTHONPATH=/home/bcook/projects/metasploit-framework/lib/msf/core/modules/external/python

$./build/linux.x86_64/bin/mettle -h
Usage: mettle [options]
  -h, --help             display help
  -u, --uri <uri>        add connection URI
  -U, --uuid <uuid>      set the UUID (base64)
  -d, --debug [level]    enable debug output
  -o, --out <file>       write debug output to a file
  -b, --background [0|1] start as a background service
  -p, --persist [none|install|uninstall] manage persistence
  -m, --modules <path>   add modules from path
  -n, --name <name>      name to start as
  -l, --listen
  -c, --console

$ ./build/linux.x86_64/bin/mettle -c -m ~/projects/metasploit-framework/modules
[+] mettlesploit! ¯\(º_o)/¯
mettle> help
Available commands:
  exit	Exit the console
  clear	Clear the screen
  back	Clear the current context
  use	Use a module
  set	Set a module option
  run	Run a module
  info	Get info on a module
  show	Show info on a module
  jobs	Job management
mettle> use auxiliary/dos/http/slowloris
mettle (auxiliary/dos/http/slowloris) > show options

Module options (auxiliary/dos/http/slowloris)
  rand_user_agent = true
  delay = 15
  ssl = false
  rhost = (null)
  sockets = 150
  rport = 80
mettle (auxiliary/dos/http/slowloris) > set rhost 127.0.0.1
rhost => 127.0.0.1
mettle (auxiliary/dos/http/slowloris) > run
[*] [auxiliary/dos/http/slowloris] Running
[*] [auxiliary/dos/http/slowloris] Attacking 127.0.0.1 with 150 sockets
[*] [auxiliary/dos/http/slowloris] Creating sockets...
[*] [auxiliary/dos/http/slowloris] Creating socket number 0
[*] [auxiliary/dos/http/slowloris] Sending keep-alive headers... Socket count: 0
[*] [auxiliary/dos/http/slowloris] Recreating socket...
mettle (auxiliary/dos/http/slowloris) > jobs
Running jobs:
  1 (auxiliary/dos/http/slowloris)
mettle (auxiliary/dos/http/slowloris) > jobs -K
[*] Killed job 1 (auxiliary/dos/http/slowloris)
mettle (auxiliary/dos/http/slowloris) > exit
```

I'd call this tech-demo quality for now, so marking as delayed.

### CODE REVIEW

**Comment by bwatters-r7** [comment]
Is this still rolling?

**Comment by busterb** [comment]
Please leave it as-is for now.

**Comment by bwatters-r7** [comment]
Maybe later?

**Comment by busterb** [comment]
Reopening to work on this again.

**Comment by busterb** [comment]
We're going to use this as the basis of some other projects as well, so moving into master to get some binary testing going and we'll fix whatever in-tree.

**Pull request merged**
